### ISSUE TITLE
Endianness detection defaults to Little-endian when including platform/toolchain's endian.h

### ISSUE THREAD

**Issue by jrhees-cae** [nestlabs/nlio#16]
The endian.h found in gnu toolchains defines all three of these:

[taken from my linux machine's /usr/include folder]
#define __LITTLE_ENDIAN 1234
#define __BIG_ENDIAN    4321
#define __PDP_ENDIAN    3412

The endianness check in nlbyteorder.h reads:

#if defined(__LITTLE_ENDIAN) || defined(__LITTLE_ENDIAN__) || (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
#define NLBYTEORDER NLBYTEORDER_LITTLE_ENDIAN
#elif defined(__BIG_ENDIAN) || defined(__BIG_ENDIAN__) || (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#define NLBYTEORDER NLBYTEORDER_BIG_ENDIAN
#else
#error "Endianness undefined!"
#define NLBYTEORDER NLBYTEORDER_UNKNOWN_ENDIAN
#endif /* defined(__LITTLE_ENDIAN) || defined(__LITTLE_ENDIAN__) || (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) */

Thus the pre-processor check will always equate to little-endian even on toolchains for big-endian (e.g., MIPS, etc).

**Comment by gerickson** [comment]
Thanks for the catch. It looks like this will need to evolve in light of that. Let me gather some data.

**Comment by gerickson** [comment]
Let me run some `echo "int main(void) { return 0; }" | {gcc,clang} -dM -E - | sort | grep END` tests on Linux and macOS and see what I can do to address this.

**Comment by jrhees-cae** [comment]
For reference, here is output for my MIPS build environment (mips-unknown-linux-uclibc):

`#define __BYTE_ORDER__ __ORDER_BIG_ENDIAN__`
`#define __FLOAT_WORD_ORDER__ __ORDER_BIG_ENDIAN__`
`#define __ORDER_BIG_ENDIAN__ 4321`
`#define __ORDER_LITTLE_ENDIAN__ 1234`
`#define __ORDER_PDP_ENDIAN__ 3412`

**Comment by gerickson** [comment]
**%** `/usr/local/gnu/share/automake-1.16/config.guess ; echo "int main(void) { return 0; }" | gcc -dM -E - | sort | grep END`:
```
x86_64-apple-darwin19.6.0
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __LITTLE_ENDIAN__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```

**Comment by gerickson** [comment]
**%** `/usr/local/gnu/share/automake-1.16/config.guess ; echo "int main(void) { return 0; }" | clang -dM -E - | sort | grep END`:
```
x86_64-apple-darwin19.6.0
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __LITTLE_ENDIAN__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```

**Comment by gerickson** [comment]
**%** `/usr/share/automake-1.16/config.guess ; echo "int main(void) { return 0; }" | gcc -dM -E - | sort | grep END`:
```
x86_64-pc-linux-gnu
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```

**Comment by gerickson** [comment]
**%** `/usr/share/automake-1.16/config.guess ; echo "int main(void) { return 0; }" | clang -dM -E - | sort | grep END`
```
x86_64-pc-linux-gnu
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __LITTLE_ENDIAN__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```

**Comment by gerickson** [comment]
**%** `echo "int main(void) { return 0; }" | /usr/local/toolchains/gcc-arm-none-eabi-4_8-2013q4/bin/arm-none-eabi-gcc -dM -E - | sort | grep END`:
```
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```

**Comment by gerickson** [comment]
@jrhees-cae, the following diff appears to work:

```
diff --git a/include/nlbyteorder.h b/include/nlbyteorder.h
index b56ffe6..f4ba9bf 100644
--- a/include/nlbyteorder.h
+++ b/include/nlbyteorder.h
@@ -1,4 +1,5 @@
 /**
+ *    Copyright (c) 2020 nlio Authors. All Rights Reserved.
  *    Copyright 2012-2017 Nest Labs Inc. All Rights Reserved.
  *
  *    Licensed under the Apache License, Version 2.0 (the "License");
@@ -177,14 +178,20 @@ extern "C" {
  *       - NLBYTEORDER_UNKNOWN_ENDIAN
  *
  */
-#if defined(__LITTLE_ENDIAN) || defined(__LITTLE_ENDIAN__) || (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
+#if defined(__BYTE_ORDER__)
+# if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
+#  define NLBYTEORDER NLBYTEORDER_LITTLE_ENDIAN
+# elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
+#  define NLBYTEORDER NLBYTEORDER_BIG_ENDIAN
+# endif /* __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__ */
+#elif defined(__LITTLE_ENDIAN__) && (__LITTLE_ENDIAN__ == 1)
 #define NLBYTEORDER NLBYTEORDER_LITTLE_ENDIAN
-#elif defined(__BIG_ENDIAN) || defined(__BIG_ENDIAN__) || (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
+#elif defined(__BIG_ENDIAN__) && (__BIG_ENDIAN__ == 1)
 #define NLBYTEORDER NLBYTEORDER_BIG_ENDIAN
 #else
 #error "Endianness undefined!"
 #define NLBYTEORDER NLBYTEORDER_UNKNOWN_ENDIAN
-#endif /* defined(__LITTLE_ENDIAN) || defined(__LITTLE_ENDIAN__) || (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) */
+#endif /* defined(__BYTE_ORDER__) */
 
 enum {
     nlByteOrderUnknown     = NLBYTEORDER_UNKNOWN_ENDIAN,
```

Do you want to give that a spin in your MIPS environment and confirm?

**Comment by jrhees-cae** [comment]
The change works on my build system. However this turns up another error, where I needed to make the following change:

```
diff --git a/include/nlbyteorder-big.h b/include/nlbyteorder-big.h
index 959604b..3b8fcd7 100644
--- a/include/nlbyteorder-big.h
+++ b/include/nlbyteorder-big.h
@@ -41,7 +41,7 @@
  */
 static inline uint16_t nlByteOrderSwap16LittleToHost(uint16_t inValue)
 {
-    return nlByteOrderSwap16(inValue);
+    return nlByteOrderValueSwap16(inValue);
 }
 
 /**
```

**Comment by gerickson** [comment]
> The change works on my build system. However this turns up another error, where I needed to make the following change:
> 
> ```
> diff --git a/include/nlbyteorder-big.h b/include/nlbyteorder-big.h
> index 959604b..3b8fcd7 100644
> --- a/include/nlbyteorder-big.h
> +++ b/include/nlbyteorder-big.h
> @@ -41,7 +41,7 @@
>   */
>  static inline uint16_t nlByteOrderSwap16LittleToHost(uint16_t inValue)
>  {
> -    return nlByteOrderSwap16(inValue);
> +    return nlByteOrderValueSwap16(inValue);
>  }
>  
>  /**
> ```

Can you clarify what exactly that error was/is (ideally copy-and-paste the compiler output) and why it only needed a change in the '16' instance of this rather than the '32' and '64' as well?

**Comment by jrhees-cae** [comment]
Sorry I should have been more specific:

```
/connectedhomeip/third_party/nlio/repo/include/nlbyteorder-big.h: In function 'uint16_t nlByteOrderSwap16LittleToHost(uint16_t)':
/connectedhomeip/third_party/nlio/repo/include/nlbyteorder-big.h:44:12: error: 'nlByteOrderSwap16' was not declared in this scope; did you mean 'nlByteOrderValueSwap16'?
   44 |     return nlByteOrderSwap16(inValue);
      |            ^~~~~~~~~~~~~~~~~
      |            nlByteOrderValueSwap16
```

This appears to be a typo in the source, as all of the other widths (32/64) have the 'ValueSwap' variant.

**Comment by gerickson** [comment]
Thanks for the catch on this @jrhees-cae!
